# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dbTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dbTable.setGeometry(QtCore.QRect(20, 10, 761, 461))
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(0)
        self.dbTable.setRowCount(0)
        self.dbSaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dbSaveBtn.setGeometry(QtCore.QRect(20, 480, 93, 28))
        self.dbSaveBtn.setObjectName("dbSaveBtn")
        self.dbDeleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dbDeleteBtn.setGeometry(QtCore.QRect(160, 480, 93, 28))
        self.dbDeleteBtn.setObjectName("dbDeleteBtn")
        self.dbLoadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dbLoadBtn.setGeometry(QtCore.QRect(690, 480, 93, 28))
        self.dbLoadBtn.setObjectName("dbLoadBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dbSaveBtn.setText(_translate("MainWindow", "Сохранить"))
        self.dbDeleteBtn.setText(_translate("MainWindow", "Удалить"))
        self.dbLoadBtn.setText(_translate("MainWindow", "Загрузить"))
