# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.searchBtn.setObjectName("searchBtn")
        self.searchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLine.setGeometry(QtCore.QRect(130, 10, 651, 22))
        self.searchLine.setObjectName("searchLine")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(20, 500, 93, 28))
        self.saveBtn.setObjectName("saveBtn")
        self.sortFilters = QtWidgets.QComboBox(self.centralwidget)
        self.sortFilters.setGeometry(QtCore.QRect(150, 50, 161, 22))
        self.sortFilters.setObjectName("sortFilters")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 131, 20))
        self.label.setObjectName("label")
        self.viewSaved = QtWidgets.QPushButton(self.centralwidget)
        self.viewSaved.setGeometry(QtCore.QRect(690, 500, 93, 28))
        self.viewSaved.setObjectName("viewSaved")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 761, 411))
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setObjectName("listWidget")
        self.loadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadBtn.setGeometry(QtCore.QRect(130, 500, 93, 28))
        self.loadBtn.setObjectName("loadBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Фильтовать по</span></p></body></html>"))
        self.viewSaved.setText(_translate("MainWindow", "View Saved"))
        self.loadBtn.setText(_translate("MainWindow", "Load"))
