# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(664, 111)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setGeometry(QtCore.QRect(180, 10, 101, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.viewsLabel = QtWidgets.QLabel(Form)
        self.viewsLabel.setGeometry(QtCore.QRect(180, 50, 101, 16))
        self.viewsLabel.setObjectName("viewsLabel")
        self.publishedLabel = QtWidgets.QLabel(Form)
        self.publishedLabel.setGeometry(QtCore.QRect(180, 70, 101, 16))
        self.publishedLabel.setObjectName("publishedLabel")
        self.durationLabel = QtWidgets.QLabel(Form)
        self.durationLabel.setGeometry(QtCore.QRect(180, 30, 101, 16))
        self.durationLabel.setObjectName("durationLabel")
        self.Name = QtWidgets.QLabel(Form)
        self.Name.setGeometry(QtCore.QRect(290, 10, 361, 16))
        self.Name.setText("")
        self.Name.setObjectName("Name")
        self.Duration = QtWidgets.QLabel(Form)
        self.Duration.setGeometry(QtCore.QRect(290, 30, 361, 16))
        self.Duration.setText("")
        self.Duration.setObjectName("Duration")
        self.Views = QtWidgets.QLabel(Form)
        self.Views.setGeometry(QtCore.QRect(290, 50, 361, 16))
        self.Views.setText("")
        self.Views.setObjectName("Views")
        self.Published = QtWidgets.QLabel(Form)
        self.Published.setGeometry(QtCore.QRect(290, 70, 361, 16))
        self.Published.setText("")
        self.Published.setObjectName("Published")
        self.imageLabel = QtWidgets.QLabel(Form)
        self.imageLabel.setGeometry(QtCore.QRect(10, 10, 160, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setMinimumSize(QtCore.QSize(160, 90))
        self.imageLabel.setText("")
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabel.setText(_translate("Form", "Название:"))
        self.viewsLabel.setText(_translate("Form", "Просмотры:"))
        self.publishedLabel.setText(_translate("Form", "Добавлен:"))
        self.durationLabel.setText(_translate("Form", "Длительность:"))
